optiscaler/OptiScaler

OptiScaler/Config.cpp, OptiScaler/Config.h, OptiScaler/Logger.cpp, OptiScaler/imgui/imgui_common.h, nvngx.ini
A master switch for logging is unnecessary given that this information can be extrapolated.
For a long time the LogEnabled setting was already set to true by default and removing it will make it less confusing for the end users.
=> Remove master logging switch

OptiScaler/Config.cpp, OptiScaler/Config.h, OptiScaler/NVNGX.cpp, OptiScaler/NVNGX_DLSS_Dx11.cpp, OptiScaler/NVNGX_DLSS_Dx12.cpp, OptiScaler/NVNGX_DLSS_Vk.cpp, OptiScaler/NVNGX_Proxy.h, OptiScaler/imgui/imgui_common.cpp, nvngx.ini
This fixes preset overriding on games like Monster Hunter Rise, that have fixed presets on ther appId inside DLSS.
=> fix: add UseGenericAppIdWithDlss

OptiScaler/backends/dlss/DLSSFeature.cpp
According to the NVIDIA docs, game devs are expected to check if a given PerfQuality mode is enabled for a DLSS version by calling NVSDK_NGX_DLSS_GetOptimalSettingsCallback and checking if the the OptimalWidth/OptimalHeight > 0.
Satisfactory does that, and if it's present, it will try to use NVSDK_NGX_PerfQuality_Value_UltraQuality as a mode for ANY DLSS mode that isn't DLAA. 
This causes the real DLSS runtime to throw an error on feature creation when used with OptiScaler, and this PR fixes that by returning that Ultra Quality isn't available when the real DLSS is enabled.
=> feat: don't return Ultra Quality to real DLSS

OptiScaler/Config.cpp, OptiScaler/Config.h, OptiScaler/imgui/imgui_common.cpp, OptiScaler/imgui/imgui_common.h
Just making fakenvapi.ini file editable in the menu. Fakenvapi starting with version 1.1.1 watches for the config file changes and applies them live. When combined with an older versions of fakenvapi, a game restart is needed.
=> Add fakenvapi settings to the menu

README.md
I forgot to do that with the initial PR, better late than never though!
=> Update README to add FSR 3.1 as a DX11 upscaler.

OptiScaler/OptiScaler.vcxproj
This fixes a race condition on start up on some RE Engine titles.
Tested on Monster Hunter Rise.
=> Delay load direct3d to make RE Engine happy

OptiScaler/Config.cpp, OptiScaler/Config.h, OptiScaler/DLSSG_Mod.h, OptiScaler/Gdi32_Proxy.h, OptiScaler/NVNGX_DLSS_Dx12.cpp, OptiScaler/NVNGX_DLSS_Vk.cpp, OptiScaler/NVNGX_Parameter.h, OptiScaler/NVNGX_Proxy.h, OptiScaler/OptiScaler.vcxproj, OptiScaler/OptiScaler.vcxproj.filters, OptiScaler/Streamline_Proxy.h, OptiScaler/Util.cpp, OptiScaler/Util.h, OptiScaler/XeSS_Proxy.h, OptiScaler/dllmain.cpp, OptiScaler/hooks/HooksDx.cpp, OptiScaler/hooks/wrapped_swapchain.cpp, OptiScaler/hooks/wrapped_swapchain.h, OptiScaler/imgui/imgui_common.cpp, OptiScaler/nvapi/NvApiHooks.h, OptiScaler/nvapi/ReflexHooks.h, OptiScaler/nvapi/fakenvapi.h, external/streamline/sl.h, external/streamline/sl_consts.h, external/streamline/sl_result.h, external/streamline/sl_struct.h, external/streamline/sl_version.h, nvngx.ini
Let's the user select DLSSG from the game settings and is mutually exclusive with Opti's own FG. The idea is very simple, just pass ngx calls that refer to FG to dlssg-to-fsr3.
Has all the required spoofing. Includes a workaround for Cyberpunk's bug causing glitched visuals on RDNA2 on Windows courtesy of Nukem as well as a depth copy that fixes many non-UE games on AMD on Windows. Also adds logging of streamline messages which might come handy.
dlssg_to_fsr3_amd_is_better.dll needs to be provided by the user.
=> Add support for dlssg-to-fsr3 mod

OptiScaler/OptiScaler.vcxproj.filters, OptiScaler/include/imgui/imgui.cpp, OptiScaler/include/imgui/imgui.h, OptiScaler/include/imgui/imgui_demo.cpp, OptiScaler/include/imgui/imgui_draw.cpp, OptiScaler/include/imgui/imgui_impl_dx11.cpp, OptiScaler/include/imgui/imgui_impl_dx12.cpp, OptiScaler/include/imgui/imgui_impl_dx12.h, OptiScaler/include/imgui/imgui_impl_vulkan.cpp, OptiScaler/include/imgui/imgui_impl_vulkan.h, OptiScaler/include/imgui/imgui_internal.h, OptiScaler/include/imgui/imgui_widgets.cpp, OptiScaler/include/imgui/misc/freetype/imgui_freetype.cpp, OptiScaler/menu/menu_base.cpp, OptiScaler/menu/menu_base.h, OptiScaler/menu/menu_common.cpp, OptiScaler/menu/menu_common.h, OptiScaler/menu/menu_dx11.cpp, OptiScaler/menu/menu_dx12.cpp, OptiScaler/menu/menu_dx_base.cpp, OptiScaler/menu/menu_dx_base.h, OptiScaler/menu/menu_overlay_base.h, OptiScaler/menu/menu_overlay_dx.cpp, OptiScaler/menu/menu_overlay_vk.cpp, OptiScaler/upscalers/IFeature_Dx12.cpp
Uses https://github.com/ocornut/imgui/pull/3761
This gives us the ability to get the correctly sampled font for the currently selected scale which generally looks sharper.
Creates two scaled fonts: 1 * scale and 3 * scale. Some system for requesting differently sized fonts can be implemented in the future. 
Uses a base class that get inherited by dx base and overlay base which don't feel quite right with the existence of menu common so I'm open to changing that if need be.
=> Dynamic font creation

OptiScaler/Config.h, OptiScaler/menu/menu_common.cpp, OptiScaler/menu/menu_common.h
Fixes xess selection not being saved on dlss-capable systems.
Keeps the option of using value_or_default() with settings that might be system dependent.
=> Fix upscaler not saving correctly

OptiScaler/OptiScaler.vcxproj, OptiScaler/State.h, OptiScaler/dllmain.cpp, OptiScaler/upscalers/dlss/DLSSFeature.cpp, OptiScaler/upscalers/dlssd/DLSSDFeature.cpp
Fixes OTA versions, displayed as 0.0.0 previously and longer DLSS versions which caused 310 to be shown as 54.
=> Fix reading of OTA dlss/dlssd versions

OptiScaler/dllmain.cpp, OptiScaler/dllmain.h, OptiScaler/nvapi/NvApiHooks.cpp, OptiScaler/nvapi/NvApiTypes.h, OptiScaler/nvapi/ReflexHooks.cpp
Unlike proper nvapi, dxvk-nvapi calls CreateDxgiFactory inside the init call which means we can't call it. GetInterfaceVersionString in dxvk-nvapi can be called without having nvapi inited so use that to identify whether we are using dxvk-nvapi and use EnumDisplayDevices to get GPU vendor instead.
=> Better deal with dxvk-nvapi

OptiScaler/OptiScaler.vcxproj, OptiScaler/OptiScaler.vcxproj.filters, OptiScaler/State.h, OptiScaler/inputs/FSR2_Dx12.cpp, OptiScaler/inputs/FfxApi_Dx12.cpp, OptiScaler/inputs/NVNGX_DLSS.h, OptiScaler/inputs/NVNGX_DLSS_Dx11.cpp, OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp, OptiScaler/inputs/NVNGX_DLSS_Vk.cpp, OptiScaler/menu/menu_common.cpp, OptiScaler/upscalers/IFeature.h, OptiScaler/upscalers/IFeature_Dx11wDx12.cpp, OptiScaler/upscalers/dlss/DLSSFeature_Dx11.cpp, OptiScaler/upscalers/dlss/DLSSFeature_Dx12.cpp, OptiScaler/upscalers/dlssd/DLSSDFeature_Dx11.cpp, OptiScaler/upscalers/dlssd/DLSSDFeature_Dx12.cpp, OptiScaler/upscalers/fsr2/FSR2Feature_Dx11.cpp, OptiScaler/upscalers/fsr2/FSR2Feature_Dx11On12.cpp, OptiScaler/upscalers/fsr2/FSR2Feature_Dx12.cpp, OptiScaler/upscalers/fsr2/FSR2Feature_Vk.cpp, OptiScaler/upscalers/fsr2_212/FSR2Feature_Dx11On12_212.cpp, OptiScaler/upscalers/fsr2_212/FSR2Feature_Dx12_212.cpp, OptiScaler/upscalers/fsr2_212/FSR2Feature_Vk_212.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx11.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx11On12.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Vk.cpp, OptiScaler/upscalers/xess/XeSSFeature_Dx11.cpp, OptiScaler/upscalers/xess/XeSSFeature_Dx12.cpp
Ties reinit variables with handle id.
Fixes a crash when trying to change an upscaler in Split Fiction
=> Allow for reinit with multiple upscalers active at the same time

OptiScaler/State.h, OptiScaler/dllmain.cpp, OptiScaler/inputs/FfxApi_Dx12.cpp, OptiScaler/inputs/FfxApi_Vk.cpp, OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp, OptiScaler/upscalers/IFeature.cpp, OptiScaler/upscalers/IFeature.h, OptiScaler/upscalers/fsr31/FSR31Feature_Dx11.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx11On12.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx11On12.h, OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp, OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.h, OptiScaler/upscalers/fsr31/FSR31Feature_Vk.cpp
Includes fixes/workarounds for:
- output scaling when using upscaleSize
- Non-FSR 3.1 upscalers not supporting upscaleSize resulting in a stretched image, emulated by reiniting the upscaler
- speeding up upscaler init to make certain transitions in Split Fiction smoother when used with Non-FSR 3.1 upscalers 
More can be done in the future
https://github.com/user-attachments/assets/c33b4f79-75b2-40f0-8766-cf0984fec9d4
=> Split Fiction fixes

OptiScaler/menu/menu_common.cpp
No scam I promise
Off by one bug, frameTime already holds one frametime before the loop meaning 101 frametimes divided by 100.
=> 1% FPS Boost

OptiScaler/hooks/HooksDx.cpp
=> Final fix for formatting

.github/workflows/test.yml
This was probably not a problem because there was always a previous nightly release. Still here is a fix for completeness sake
=> ci: run release check before creation

OptiScaler/State.h, OptiScaler/dllmain.cpp, OptiScaler/hooks/HooksVk.cpp, OptiScaler/hooks/Kernel_Hooks.h, OptiScaler/pch.h
AMD drivers on the cards around RDNA2 didn't treat VK_IMAGE_LAYOUT_UNDEFINED in the same way Nvidia does. Doesn't seem like a bug, just a different way of handling an UB but we need to adjust.
Resolves: https://github.com/cdozdil/OptiScaler/issues/29
=> Fix graphical corruptions in No Man's Sky on older AMD cards

OptiScaler/hooks/Advapi32_Hooks.h
Fixes crashes on certain FFXIV plugins.
=> Null check lpSubKey before comparing it.

OptiScaler.ini, OptiScaler/Config.cpp, OptiScaler/Config.h, OptiScaler/DllNames.h, OptiScaler/Logger.cpp, OptiScaler/OptiScaler.vcxproj, OptiScaler/OptiScaler.vcxproj.filters, OptiScaler/State.h, OptiScaler/dllmain.cpp, OptiScaler/hooks/Crypt32_Hooks.h, OptiScaler/hooks/Kernel_Hooks.h, OptiScaler/hooks/Streamline_Hooks.cpp, OptiScaler/hooks/Streamline_Hooks.h, OptiScaler/include/sl.param/parameters.cpp, OptiScaler/include/sl.param/parameters.h, OptiScaler/nvapi/ReflexHooks.cpp, external/streamline/sl_reflex.h, external/streamline1/sl1_reflex.h
It is enabled by default so in some cases users should see DLSS, DLSSG and/or Reflex show up even with Dxgi spoofing disabled.
Reflex can often be force enabled if fakenvapi is added, even if the game settings don't allow for activating it. But the results vary.
=> Add spoofing for just Streamline

OptiScaler/hooks/Streamline_Hooks.cpp
Should fix crashes that seem to appear in sl 2.4.10 with slDLSSGSetOptions in DX12 games.
=> Limit DLSSG options hook to Vulkan

OptiScaler/FSR4Upgrade.h, OptiScaler/hooks/Kernel_Hooks.h
amdxcffx64.dll is still needed, it contains the FSR 4 itself.
=> Remove the need for amdxc64 on Linux

OptiScaler/hooks/Streamline_Hooks.cpp
Streamline spoofing now shouldn't show DLSSG in game settings when DLSSG cannot be used.
=> More selective DLSSG enablement

setup_linux.sh
Maybe need more users test, but I tested on Nixos, and it works also on Archlinux.
On NixOS, /bin/bash not exist at all, and it's recommended to use /usr/bin/env bash. 
This executable exists also on Archlinux and normally exist on all Linux distributions.
=> setup_linux.sh: Use more generic bash
