optiscaler/OptiScaler

- OptiScaler/imgui/imgui_common.h
To make navigating the menu easier for new users
> Add help tips to the overlay

- OptiScaler/NVNGX_DLSS_Dx12.cpp
- OptiScaler/NVNGX_Proxy.h
- OptiScaler/OptiScaler.vcxproj
- OptiScaler/OptiScaler.vcxproj.filters
- OptiScaler/fakenvapi.h
- OptiScaler/hooks/HooksDx.cpp
- OptiScaler/hooks/HooksDx.h
- OptiScaler/pch.h
Requires this fakenvapi commit or later https://github.com/FakeMichau/fakenvapi/commit/fff735a0be66419bf0a04b8c03ddac7322a25c4d
> AnitLag 2 support for Opti's FG

- OptiScaler/Config.cpp
- OptiScaler/Config.h
- OptiScaler/dllmain.cpp
- OptiScaler/dllmain.h
- OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp
- OptiScaler/inputs/NVNGX_DLSS_Vk.cpp
- OptiScaler/menu/menu_common.cpp
- OptiScaler/menu/menu_common.h
- OptiScaler/proxies/NVNGX_Proxy.h
- OptiScaler/upscalers/fsr2/FSR2Feature_Dx11.cpp
- OptiScaler/upscalers/fsr2/FSR2Feature_Dx11On12.cpp
- OptiScaler/upscalers/fsr2/FSR2Feature_Dx12.cpp
- OptiScaler/upscalers/fsr2/FSR2Feature_Vk.cpp
- OptiScaler/upscalers/fsr2_212/FSR2Feature_Dx11On12_212.cpp
- OptiScaler/upscalers/fsr2_212/FSR2Feature_Dx12_212.cpp
- OptiScaler/upscalers/fsr2_212/FSR2Feature_Vk_212.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx11.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx11On12.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Vk.cpp
- OptiScaler/upscalers/xess/XeSSFeature_Dx12.cpp
- nvngx.ini
Every should be done. Also adds a config for an AMD workaround as it has started to cause issues with streamline 2.7.
> Config improvements part 3

- OptiScaler/Config.cpp
- OptiScaler/menu/menu_common.cpp
- OptiScaler/upscalers/dlss/DLSSFeature.cpp
- OptiScaler/upscalers/dlssd/DLSSDFeature.cpp
Should make the new presets mostly usable, but DLAA/Ultra Quality/Ultra Performance don't seem to be changeable in my limited testing.
Quality/Balanced/Performance preset setting works fine.
> DLSS preset fixes

- Config.md
- Issues.md
- OptiScaler.ini
- OptiScaler/Config.cpp
- OptiScaler/Config.h
- OptiScaler/DLSSG_Mod.h
- OptiScaler/OptiScaler.vcxproj
- OptiScaler/State.h
- OptiScaler/dllmain.cpp
- OptiScaler/hooks/HooksDx.cpp
- OptiScaler/hooks/wrapped_swapchain.cpp
- OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp
- OptiScaler/menu/menu_common.cpp
- OptiScaler/menu/menu_common.h
- OptiScaler/nvapi/NvApiHooks.h
- OptiScaler/proxies/Gdi32_Proxy.h
- OptiScaler/proxies/NVNGX_Proxy.h
- OptiScaler/proxies/Streamline_Proxy.h
- README.md
- Spoofing.md
Moved config stuff around to make it easier to add other FG tech in the future. Because of this and the config rename this is a breaking change and requires the user to create a new config.
Wiki entries might need to get adjusted
> Make FG selection a dropdown + config rename

- OptiScaler/OptiScaler.vcxproj
- OptiScaler/OptiScaler.vcxproj.filters
- OptiScaler/State.h
- OptiScaler/hooks/HooksDx.cpp
- OptiScaler/hooks/wrapped_swapchain.cpp
- OptiScaler/menu/menu_common.cpp
- OptiScaler/misc/FrameLimit.cpp
- OptiScaler/misc/FrameLimit.h
- OptiScaler/nvapi/ReflexHooks.h
- OptiScaler/pch.h
Takes some code from fakenvapi. Found issues with reflex on the way that may need to be fixed in the future but a warning for now will do.
> Add a fallback way of limiting FPS when can't use Reflex

- OptiScaler/menu/menu_common.cpp
- OptiScaler/menu/menu_common.h
- OptiScaler/upscalers/dlss/DLSSFeature.cpp
- OptiScaler/upscalers/dlss/DLSSFeature_Dx12.cpp
- OptiScaler/upscalers/dlssd/DLSSDFeature.cpp
Generally just a clean up. Should make it easy to have separate render presets for DLSS and DLSSD in the config if need be.
> Separate out DLSS from DLSSD + extra related

- OptiScaler/dllmain.cpp
- OptiScaler/proxies/XeSS_Proxy.h
Experimenting a bit with macros, for now the variable names across the codebase are too inconsistent to be used more widely.
> Fix xess hooks

- OptiScaler/menu/menu_common.cpp
- OptiScaler/menu/menu_common.h
Using a simple class to not have to worry about unindenting
> Add indents to collapsing menus

- Features.md
- README.md
Added a Table of Contents, separated Full Features list into its own Features.md, "beautified" the readme, added collapsible sections for extra info
> Update Readme.md - part 8

- OptiScaler/menu/menu_common.cpp
Tries to display a user-friendly name of the key. Escape and Backspace cancel the rebind process. R button for resetting the keybind to default.
> Add rebinding to the menu

- .github/ISSUE_TEMPLATE/crash-bug.md
- OptiScaler.ini
- README.md
> docs: unify OptiScaler spelling

- OptiScaler.ini
- OptiScaler/Config.cpp
- OptiScaler/Config.h
- OptiScaler/menu/menu_common.cpp
Resolves: https://github.com/cdozdil/OptiScaler/issues/517
> Allow for unbinding keybinds from the menu

- OptiScaler/State.h
- OptiScaler/dllmain.cpp
- OptiScaler/hooks/Kernel_Hooks.h
- OptiScaler/hooks/Streamline_Hooks.cpp
- OptiScaler/include/flag-set-cpp/flag_set.hpp
- OptiScaler/inputs/FSR3_Dx12.cpp
- OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp
Allows one game to have multiple quirks as well as allows for easier sharing of quirks between games
> Turn game quirks into flags

- OptiScaler/dllmain.cpp
- OptiScaler/proxies/FfxApi_Proxy.h
- OptiScaler/upscalers/fsr31/FSR31Feature.h
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx11On12.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp
Should fix cases where FSR 4 works only on Linux
> Implement typeless conversions for FSR 4 

- OptiScaler/dllmain.cpp
Resolves: https://github.com/cdozdil/OptiScaler/issues/530
Thanks to @MapleHinata for immediately recognizing the root cause
> Workaround the ntdll-Hide_Wine_Exports patch

- OptiScaler/OptiScaler.vcxproj
- setup_linux.sh
- setup_windows.bat
Renames the Windows script to setup_windows.bat and the Linux one to setup_linux.sh
> Linux script fixups

- OptiScaler/hooks/Streamline_Hooks.cpp
> Don't force disable Reflex at the Streamline level

- OptiScaler/NVNGX_Parameter.h
- OptiScaler/State.h
- OptiScaler/dllmain.cpp
- OptiScaler/inputs/NVNGX_DLSS_Dx12.cpp
- OptiScaler/upscalers/IFeature.cpp
- OptiScaler/upscalers/fsr2/FSR2Feature_Dx12.cpp
- OptiScaler/upscalers/fsr2_212/FSR2Feature_Dx12_212.cpp
- OptiScaler/upscalers/fsr31/FSR31Feature_Dx12.cpp
- OptiScaler/upscalers/xess/XeSSFeature_Dx12.cpp
Improves application of engine-specific fixes.
> Updates to engine information

- OptiScaler/dllmain.cpp
- OptiScaler/misc/Quirks.h
All of them work with sl spoofing alone
> Disable Dxgi spoofing by default for select games

- OptiScaler/State.h
- OptiScaler/menu/menu_common.cpp
- OptiScaler/nvapi/ReflexHooks.cpp
> Detect RTSS Reflex injection

- OptiScaler/misc/Quirks.h
* Added Hitman 3/WoA, Returnal, Uncharted LoT
* Added more comments for future reference
> Added more game quirks
